apiVersion: v1
kind: Pod
metadata:
  name: pod-containers
spec:
  containers:
  - name: container-nginx
    image: nginx
  - name: phpmyadmin
    image: phpmyadmin
  - name: mariadbContainer
    image: mariadb
  - name: rabbitContainer 
    image: rabbitmq
  - name: elasticContainer
    image: elasticsearch:8.10.2

#create the same containers but with name is just lowercase letters
#see how to create the network in which the containers inside this pod will be connected
#make sure that all containers are inside of it and talking to each other