apiVersion: v1
kind: Pod
metadata:
  name: mariadb-pod
spec:
  containers:
    - name: container-mariadb
      image: mariadb:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
      ports:
        - containerPort: 1925
